exports.seed =async function(knex) {
  await knex('drink').del()   // Deletes ALL existing entries
  await knex('drink').insert([
    {name: 'Cà Phê Sữa Đá',size:'S',price:20000,category_id:1,description:'Cà phê sữa đá thơm ngon.',stock:20,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Cà Phê Sữa Đá',size:'M',price:25000,category_id:1,description:'Cà phê sữa đá thơm ngon.',stock:15,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Cà Phê Sữa Đá',size:'L',price:30000,category_id:1,description:'Cà phê sữa đá thơm ngon.',stock:10,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa',size:'S',price:30000,category_id:0,description:'Trà sữa thơm ngon, mát lạnh.',stock:25,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa',size:'M',price:35000,category_id:0,description:'Trà sữa thơm ngon, mát lạnh.',stock:20,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa',size:'L',price:40000,category_id:0,description:'Trà sữa thơm ngon, mát lạnh.',stock:15,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Sinh Tố Bơ',size:'S',price:25000,category_id:3,description:'Sinh tố bơ tươi ngon.',stock:10,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Sinh Tố Bơ',size:'M',price:30000,category_id:3,description:'Sinh tố bơ tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Sinh Tố Bơ',size:'L',price:35000,category_id:3,description:'Sinh tố bơ tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Ép Cam',size:'M',price:20000,category_id:4,description:'Nước Ép Cam tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Ép Cam',size:'L',price:25000,category_id:4,description:'Nước Ép Cam tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Soda Chanh',size:'M',price:15000,category_id:2,description:'Soda Chanh tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Soda Chanh',size:'L',price:20000,category_id:2,description:'Soda Chanh tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Cà Phê Đen',size:'S',price:20000,category_id:1,description:'Cà phê đen đậm đà.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Matcha Latte',size:'M',price:15000,category_id:0,description:'Matcha Latte tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Matcha Latte',size:'L',price:20000,category_id:0,description:'Matcha Latte tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Cacao',size:'M',price:15000,category_id:1,description:'Cacao tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Cacao',size:'L',price:20000,category_id:1,description:'Cacao tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Dừa',size:'M',price:15000,category_id:2,description:'Nước Dừa tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Dừa',size:'L',price:20000,category_id:2,description:'Nước Dừa tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Đào',size:'M',price:15000,category_id:4,description:'Trà Đào tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Đào',size:'L',price:20000,category_id:4,description:'Trà Đào tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Sữa Chua',size:'M',price:15000,category_id:4,description:'Sữa Chua tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Sữa Chua',size:'L',price:20000,category_id:4,description:'Sữa Chua tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Mía',size:'M',price:15000,category_id:2,description:'Nước Mía tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Mía',size:'L',price:20000,category_id:2,description:'Nước Mía tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Chanh Muối',size:'M',price:15000,category_id:2,description:'Nước Chanh Muối tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Nước Chanh Muối',size:'L',price:20000,category_id:2,description:'Nước Chanh Muối tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa Trân Châu',size:'M',price:15000,category_id:0,description:'Trà Sữa Trân Châu tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa Trân Châu',size:'L',price:20000,category_id:0,description:'Trà Sữa Trân Châu tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},  
    {name: 'Trà Sữa Matcha Trân Châu',size:'M',price:15000,category_id:0,description:'Trà Sữa Matcha Trân Châu tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa Matcha Trân Châu',size:'L',price:20000,category_id:0,description:'Trà Sữa Matcha Trân Châu tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},  
    {name: 'Trà Sữa Hoa Quả',size:'M',price:15000,category_id:0,description:'Trà Sữa Hoa Quả tươi ngon.',stock:8,image:'ms-appx:///Assets/images.jpeg'},
    {name: 'Trà Sữa Hoa Quả',size:'L',price:20000,category_id:0,description:'Trà Sữa Hoa Quả tươi ngon.',stock:5,image:'ms-appx:///Assets/images.jpeg'},  
  ]);
};